---
- name: Run role
  hosts: all
  become: true
  any_errors_fatal: true

  roles:
    - role: ansible-system_upgrade

  vars:
    upgrade_simulation: false
    upgrade_pkgs_confirmation: false
    upgrade_reboot_confirmation: false
    upgrade_autoreboot: true
    upgrade_clean: true
