---
- name: "REDHAT | Collect upgradable packages"
  ansible.builtin.command: yum check-update
  register: pkglist
  changed_when: false
  failed_when: false

- name: "REDHAT | Show pending updates"
  ansible.builtin.debug:
    var: pkglist.stdout_lines
  changed_when: false

- name: "REDHAT | Upgrade all packages"
  ansible.builtin.yum:
    name: "*"
    state: latest

#- name: "Autoremove unneeded packages installed as dependencies"
#  ansible.builtin.yum:
#    autoremove: yes
